### ISSUE TITLE
ImportError: No module named tileserver.cache

### ISSUE THREAD

**Issue by musicformellons** [mapzen/tileserver#103]
I updated from tileserver v2.0.0 and tilequeue v1.7.0  to tileserver v2.1.0 and tilequeue v1.8.0 and now when trying to run the server I get:
```
root@vps405830:/home/usr/tileserver# python tileserver/__init__.py config.yaml
Traceback (most recent call last):
  File "tileserver/__init__.py", line 14, in <module>
    from tileserver.cache import CacheKey
ImportError: No module named tileserver.cache

```

I am using an ansible script which worked fine before. After changing versions I get the error. I can also not import tileserver when in Python.

**Comment by musicformellons** [comment]
Mmh, can also not import tileserver when in Python.

**Comment by zerebubuth** [comment]
After updating, did you run `python setup.py develop` again? The `tileserver.cache` file was added in the latest version but it sounds like it might still be finding the old version.

**Comment by musicformellons** [comment]
It is something in the ansible script..., I can manually delete en setup tileserver and then it runs normally... Thanks.
