### ISSUE TITLE
psycopg2.ProgrammingError

### ISSUE THREAD

**Issue by rwrx** [mapzen/tileserver#109]
I tried to run tileserver on my machine by following this tutorial: https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service . Everything was installed successfully but when I try to retrieve tile from this server I get an error `psycopg2.ProgrammingError`: `ProgrammingError: function jsonb_build_object(unknown, unknown, unknown, bigint, unknown, unknown, unknown, real) does not exist LINE 8: jsonb_build_object( ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts.` from file `query.py` from `tilequeue` library. I am also attaching screenshot:

![crash](https://user-images.githubusercontent.com/2378743/28342391-450a1b96-6c18-11e7-870c-213e8a9f0a9a.png)

For all libraries I am using master branch as when I tried to use versions recommended in that tutorial I get another errors in Python. 

I am not sure whether to post this issue into tilequeue or vector-datasource repository.

**Comment by nvkelso** [comment]
@rwrx Reporting the error here is good. Rob will have a look once he's back in the office (probably Wednesday NYC time).

**Comment by rmarianski** [comment]
We started requiring later versions of postgresql. You'll need at least 9.5, and we're running 9.6 on servers ourselves.

This is a recent change and we haven't updated the docs yet. I made an issue for that: https://github.com/tilezen/vector-datasource/issues/1319

If you can't update postgresql, I'd suggest running off the latest tagged versions which you can find here: https://github.com/tilezen/vector-datasource/releases/tag/v1.4.0

**Comment by rwrx** [comment]
Thank you a lot for your answer. I have installed postgresql 9.6 and postgis 2.3 as is written here https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service/_compare/d3ec978d8a61c13760688fdfe312859453f94051...8fe772e1f7eedbf5b159e5da0f508a29ac8ab2fe . But now I get another error when trying to retrieve tiles from tileserver. I have followed again steps from this tutorial https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service and used that New York extract and used master branches on vector-datasource, tileserver and also on tilequeue. Error message is: `NameError: name 'area' is not defined`. Here is also screenshot:

![crash2](https://user-images.githubusercontent.com/2378743/28502793-821bcd64-6ffa-11e7-8e8d-dc0288ec5708.png)

**Comment by nvkelso** [comment]
@rwrx We'll have a look Monday. In the meantime, the latest tagged releases in each repo are probably your best bet.

**Comment by rmarianski** [comment]
I tried to reproduce in a clean environment, but it worked for me. Based on your error, it looks like the database is not in a valid state. Can you try dropping your database, creating it again and re-importing the data?

**Comment by rwrx** [comment]
Thank you. Did you try also master branches, New York extract and postgresql 9.6 and postgis 2.3? I have tried it several times and dropped databases.

**Comment by rwrx** [comment]
When I follow that tutorial and checkout all that latest stable versions as are written in tutorial I get error `TypeError: process_coord_no_format() takes exactly 5 arguments (4 given)`. Is it possible for you to send me install instructions which are working for you? Or at least send parts where your instructions differ from tutorial? Do you also use Ubuntu 14.04 with updated software?

**Comment by rmarianski** [comment]
> Thank you. Did you try also master branches, New York extract and postgresql 9.6 and postgis 2.3? I have tried it several times and dropped databases.

I just tested it with a different extract, master branches and postgresql 9.5 and postgis 2.2 on ubuntu 16.04. Locally I develop with postgresql 9.6 and postgis 2.3 on ubuntu 14.04. The package versions you have installed look fine to me.

> TypeError: process_coord_no_format() takes exactly 5 arguments (4 given)

This time the error looks like it's a version mismatch between tileserver and tilequeue. If you were switching branches, I bet it's picking up an unexpected installed version, or something to that effect. If you install from requirements and then also checkout and switch branches, sometimes you can get into a state where it's picking up the installed egg instead of the checked out branch.

We are testing a docker setup that is what we plan on eventually switching to. It's early, but you can give that a try to see if it'll help. We don't have public docs for it yet, but it's a docker-compose environment.

https://github.com/tilezen/tileserver/tree/iandees/dockerize

To load the data, there's a docker script in https://github.com/tilezen/vector-datasource/tree/iandees/dockerize

Alternatively, if you send me a transcript of what you're running with console output, I can scan through to see if I can figure it out or suggest things to try.

**Comment by rwrx** [comment]
Thank you a lot for your patience.

Ok, I have done clean install on clean Ubuntu 14.04 with postgresql 9.6 and postgis 2.3 and on master branches for vector-datasource, tileserver and tilequeue. Now I don't have time to import whole planet so I imported this extract http://download.geofabrik.de/europe/slovakia.html into postgresql database. I have also followed all tutorial and another change I have done (beside different extract) is adding repository for downloading postgresql 9.6 and postgist 2.3 as is written here for Ubuntu 14.04 https://askubuntu.com/questions/831292/how-to-install-postgresql-9-6-on-any-ubuntu-version .

After successfully running server when I try for example get tile from this url http://localhost:8080/all/5/18/10.json I get `NameError: name 'area' is not define` same error as in my second post in this thread. You can reproduce this very simply just by following steps in tutorial.

This tileserver is not supposed to work with OSM extracts? When I will import whole planet (which will take approx one day on my machine - I have tested only Europe import which has taken half a day) will it work?

I just need this to work as soon as possible because I need to create mbtiles for offline maps for every country in the world and I cannot use your server for this.

**Comment by nvkelso** [comment]
@rwrx We strongly recommend using latest tagged releases in the repos for production work like this. Are those not working for you? I've listed them below for reference.

- https://github.com/tilezen/vector-datasource/releases/tag/v1.4.0-docs1
- https://github.com/mapzen/tileserver/releases/tag/v2.1.0
- https://github.com/mapzen/tilequeue/releases/tag/v1.8.0
- https://pypi.python.org/pypi/mapbox-vector-tile/v1.2.0

I agree that we should investigate `NameError: name 'area' is not define` in any case, but please try the latest tagged releases above.

**Comment by nvkelso** [comment]
@rwrx If you require any additional support please review the Premium support section at https://mapzen.com/pricing/.

**Comment by rwrx** [comment]
Thank you. I have tried it again from scratch with dropping database and cloning all repositories and checkouting tags as you wrote and I am again getting error as I wrote previously `TypeError: process_coord_no_format() takes exactly 5 arguments (4 given)`. Here is screenshot:

![crash3](https://user-images.githubusercontent.com/2378743/28592631-f1379936-7189-11e7-9c5c-db668811e621.png)

It seems that tileserver 2.1.0 and tilequeue 1.8.0 are not compatible. I have also tried tilequeue 1.9.0 as it is latest release and I get the same error.

**Comment by rmarianski** [comment]
Looks like that should have read `tilequeue 1.9.0` instead, but you tried that? We're running this version combination in production currently:

```
      "vector_datasource": "v1.3.0",
      "tilequeue": "v1.9.0",
      "mapbox_vector_tile": "v1.2.0",
      "tileserver": "v2.1.0"
```

**Comment by rwrx** [comment]
I tried tilequeue 1.9.0 but I get same error as I wrote. But now I have done checkout to master on all repositories and rerun all python configuration and it is working! :) I don't know why but I have done this previously and back then it wasn't working.

**Comment by nvkelso** [comment]
Great to hear! Good luck with the per-country builds :)
