### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by rwrx** [mapzen/tileserver#111]
I have successfully deployed tileserver on my local machine for creating mbtiles locally. On that machine I have Samsung 960 PRO 2 TB sdd, 32 GB of RAM and Intel i5 6600 cpu. I have also currently imported Europe extract into postgresql database and tile requests are really slow on this machine. I have didn't enabled caching as it caused some problems when I enabled it. I was thinking about upgrading system to some multicore AMD Ryzen cpu as this current cpu has only 4 cores. Maybe AMD Threadripper 1950X (16 cores 32 threads) when it will be released. Does tileserver speed of responding to requests benefit from cpu with multiple cores? Do you have some benchmarks? I can also see that responses are faster when there are less objects on current tile. Thank you.

**Comment by pnorman** [comment]
Performance characteristics are likely to be very similar to other examples of tile rendering, and a lot has been written about that. The important points are

- caching is key
- suitable partial indexes generally help lower zoom performance
- fast drives are essential
- RAM is needed for RAM cache
- the workload parallizes very well

Given the rest of your system specifications, you are probably CPU bound.

**Comment by nvkelso** [comment]
For Mapzen's hosted SaaS version of Tilezen we use Amazon's AWS and host the data in RDS and then point multiple EC2 tilequeue workers at those RDS databases with jobs in an SQS queue. If there's any true-ism for scaling it's that you can scale up until some new bounds are hit ;) 

(There are public Chef repos for getting Tilezen to work in AWS if that's your cup of tea.)

**Comment by rwrx** [comment]
Thank you a lot for your answers.
