### ISSUE TITLE
Tileserver is not accepting remote connections

### ISSUE THREAD

**Issue by eclipse1985** [mapzen/tileserver#113]
Hi,

I installed successfully the tileserver, and it handles request correctly, but only if I try from local machine (ex. curl http://localhost:8080/all/16/19293/24641.json). If I try from a remote machine (ex. http://[remoteip]:8080/all/16/19293/24641.json, the tileserver doesn't accept remote connection.
All stuffs related to firewall and ports are properly configured.
There is some parameter to tweak in order to handle remote requests?

Thanks

**Comment by rmarianski** [comment]
In config.yaml, set the server host to 0.0.0.0.

Note that in a production environment you'll want to run it through a different server, like gunicorn.
