### ISSUE TITLE
Error with python setup.py develop, install directory is hard-coded (or sudo is required)

### ISSUE THREAD

**Issue by radumas** [mapzen/tileserver#114]
Running `python setup.py develop` produces the following error:
```shell
running develop
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

   [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-31955.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

   /usr/local/lib/python2.7/dist-packages/
```
Does this not defeat the purpose of using a virtual environment? Should sudo be required?

**Comment by radumas** [comment]
Sorry, this was actually our mistake.

**Comment by rmarianski** [comment]
Looks like the virtualenv wasn't activated first to me, but glad you got it working regardless.

**Comment by radumas** [comment]
yeah, there was a series of mistakes. First I moved the virtualenv and my colleague was getting errors, then I recreated it but then he hadn't activated the new one, nor did he have write permissions...

We got it figured out though :innocent:
