### ISSUE TITLE
My Server seems very slow in serving tiles,pls explain how to add tilequeue for buffering

### ISSUE THREAD

**Issue by peldhose** [mapzen/tileserver#129]
Hi , 
Thank a lot for providing such an awesome opensource ... you guys are awesome ..
I configured everything as per tutorial,but my server seems very slow in delivering tiles.Pls help us to make it smooth..

**Comment by peldhose** [comment]
Can somebody pls help me to resolve this issue, 
when i run server (2TB SSD + m4.Large) , response is very slow and its stuck normally ,also am getting this error too .. 

Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 200, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 181, in write
    self.wfile.write(data)
IOError: [Errno 32] Broken pipe

**Comment by rmarianski** [comment]
Some tiles are expected to be slow, and it tends to be zoom level and area dependent. As you suggested in the issue title, you can look into pre-generating tiles to help, which is what using tilequeue will allow you to do. You can also cache tiles for extended periods of time. To get started with tilequeue, I'd suggest going through the README and the sample configuration. Generally you want to first "seed" tiles to add them to a work queue, and then "process" them which pulls them from the queue and generates tiles.

If that's the whole stack trace, then I expect it's ok. It looks like it's just that clients timed out waiting for a response, and when the server tried to send the response the socket was closed.

**Comment by peldhose** [comment]
hi @rmarianski , thankyou for reply. 
actually i have gone through README and conf.yaml.sample a lot but coulnd't find any info to properly run tilequeue and cache to manage this issues.Saw buffer {} but no more samples to get through.It will be greatfull if you can give me a sample of tilequeue running command.
also redis is installed on server and uncommented redis option in config, but doesnt seem its connecting to redis for caching.. 

thank you in advance

**Comment by rmarianski** [comment]
I'm guessing the confusion is coming from the fact that tilequeue doesn't generate artifacts that tileserver can directly consume. In our production environment, tileserver was only meant to handle requests for tiles that weren't pre-generated. In other words, if the tile was generated, it wouldn't even see the request.
There was a separate component that was responsible for satisfying those requests, [tapalcatl](https://github.com/tilezen/tapalcatl). tilequeue would write tiles to s3, and then tapalcatl would read from that s3 location to try and satisfy those requests. We also had a cache sitting in front of everything that would manage the communication, which was to try tapalcatl, and if it got a 404 then it would send the request to tileserver.
The easiest bit to set up would be the redis cache for tileserver. The code that sets that up is here: https://github.com/tilezen/tileserver/blob/a8be93ea911ef5b6a9511e482af687971d18e6c6/tileserver/__init__.py#L367-L387
I'd suggest ensuring the redis path gets triggered on startup, and if not figuring out why that is. I'd expect this config to work:
```
cache:
  type: redis
  redis:
    url: redis://localhost:6379
    options:
      # prefix added onto saved keys for namespace purposes
      key_prefix: tiles
      # time in seconds to keep key in cache
      expires: 900
```

**Comment by rmarianski** [comment]
By the way, in case you happen to be interested and haven't seen this: https://mapzen.com/blog/long-term-support-mapzen-maps/

**Comment by peldhose** [comment]
Hey ... very much thankyou for the info ... i was looking for the exact info..
