### ISSUE TITLE
table missing in the postgresql database

### ISSUE THREAD

**Issue by lechembal** [mapzen/tileserver#15]
hello everyone,

I am just starting and I want to install the mapzen tileserver on my raspberry pi 2.
I have folllowed the process described on the mapzen tileserver  Wiki .  
At the end, when starting my server locally, and typing  this request( http://localhost:8080/all/16/19293/24641.json), still have the same error   "**ProgrammingError: column "mz_transit_level" does not exist LINE 26: AND mz_transit_level <= 16 ^**

**Comment by zerebubuth** [comment]
Hi!

Wow, Map-Pi, that's cool :smile:

The `mz_transit_level` column is added by [this SQL file](https://github.com/mapzen/vector-datasource/blob/master/data/apply-planet_osm_line.sql#L9), which should have been run as part of [perform-sql-updates.sh](https://github.com/mapzen/vector-datasource/blob/master/data/perform-sql-updates.sh), when loading additional data as [part of the install](https://github.com/mapzen/vector-datasource/wiki/Mapzen-Vector-Tile-Service#user-content-load-additional-data-and-update-database). Did you notice any errors when you ran that step?

It might be worth re-running that single SQL file (or the whole `perform-sql-updates.sh`, if the other additional columns are missing from other tables), using something like this:

``` bash
psql -f apply-planet_osm_line.sql -d YOUR_DATABASE_NAME
```

Along with any additional `psql` parameters (users, passwords, etc...) that you might need for your local setup.

Hope that helps!

**Comment by lechembal** [comment]
thanks zerebubuth for your help, your command  is working but now I have different errors when I start the script perform-sql-updates.sh.
for example  I have the following error when updating the database :  E**RROR column "mz_poi_min_zoom" of relation "planet_osm_point" already exists**
the matter is that the server return the same error as the one on my first post; but about mz_poi_min_zoom

**Comment by zerebubuth** [comment]
Ah. There's also a `mz_poi_min_zoom` in [planet_osm_polygon](https://github.com/mapzen/vector-datasource/blob/master/data/apply-planet_osm_polygon.sql), perhaps it's that one which is giving the error? Please try running:

```
psql -f apply-planet_osm_polygon.sql -d YOUR_DATABASE_NAME
```

And see if that fixes the problem.

**Comment by lechembal** [comment]
yes sorry to disturb you again , in fact I thinkthe first error is coming from the functions.sql file 
**ERROR: column "inception" does not exists**

**Comment by zerebubuth** [comment]
That's odd... The `inception` column of the `wof_neighbourhood` table is added [when the table is created](https://github.com/mapzen/vector-datasource/blob/master/data/wof-schema.sql#L21). Are you using a particular version or tag of vector-datasource, or the master branch?

You could try running:

``` bash
psql -c "DROP INDEX IF EXISTS wof_neighbourhood_label_position_index; DROP INDEX IF EXISTS wof_neighbourhood_min_zoom_index; DROP INDEX IF EXISTS wof_neighbourhood_max_zoom_index; DROP TABLE IF EXISTS wof_neighbourhood; DROP TABLE IF EXISTS wof_neighbourhood_placetype;" -d YOUR_DATABASE_NAME
```

That might print out a bunch of "does not exist" messages, which are safe to ignore. Then run:

``` bash
psql -f wof_schema.sql -d YOUR_DATABASE_NAME
```

That should re-create the WOF tables, and when you verify them, they should have the `inception` column.

**Comment by rmarianski** [comment]
The database was probably created from the snapshot that we have on s3. I bet that doesn't have the inception stuff in there. We should probably just put up a new snapshot, and automate creating it on a regular basis.

**Comment by zerebubuth** [comment]
@rmarianski that's a good point. I think you're right. I've added mapzen/vector-datasource#518 to track this and discuss what the appropriate solution is.

**Comment by nvkelso** [comment]
@lechembal Can you confirm your configuration is working now, please?

**Comment by lechembal** [comment]
Hello,
It's Still not working, I am planning to restart all the configuration from
scratch.
I Will tell u this afternoon if it's working

Sincerely
Le 10 févr. 2016 20:12, "Nathaniel V. KELSO" notifications@github.com a
écrit :

**Comment by nvkelso** [comment]
Closing this old issue as we think we fixed it. Please reopen or create a new issue if you run into the problem again.
