### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by songololo** [mapzen/tileserver#30]
Is there a way to set the access control headers for tileserver?

I am getting these errors:
`No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by rmarianski** [comment]
There isn't at the moment, no. We usually have another server in front of tileserver that always adds those headers into the response. Is it possible for you to add nginx in front to add those headers in?

**Comment by rmarianski** [comment]
We've added a cors configuration option to the config file. Can you try the master branch with `cors: true` configured at the top level?

**Comment by songololo** [comment]
Thanks! Works now.
