### ISSUE TITLE
Add generate script

### ISSUE THREAD

**Issue by nvkelso** [mapzen/tileserver#37]
To preseed tiles in a given area, similar to https://github.com/tilezen/joerd/blob/master/scripts/generate.py or TileStache seed.

**Comment by rmarianski** [comment]
imho tilequeue is better suited for this because it already does offline processing. Currently, this is possible with the `seed` and `process` commands, but we can add a new command to make it easier if we think there's a common use case for this, maybe matching the TileStache options.

**Comment by nvkelso** [comment]
Closing as tilequeue is better for this.
