### ISSUE TITLE
Always query for all layer data

### ISSUE THREAD

**Issue by rmarianski** [mapzen/tileserver#4]
Some of the post processing transform steps can dynamically create layers, and have implicit dependencies on source layer data to be present. To keep things simple, we should always get the query data for all layers, regardless of the request, and just prune the list of layers afterwards as necessary.

**Comment by nvkelso** [comment]
How do we verify this one?

**Comment by zerebubuth** [comment]
We can query for a layer which depends on another - for example roads being intercut with landuse - for a tile which doesn't yet exist. The previous behaviour was to fetch the "all layers" tile if it existed, but query only the requested layers if it didn't. The behaviour now is to always query all layers.

To test:
1. Find a tile which hasn't already been rendered, which has a road going through a landuse area. (E.g: 17/49568/68806 in the middle of the Amazon, hasn't been rendered to high probability).
2. Request **only the roads layer**, e.g: http://vector.dev.mapzen.com/osm/roads/17/49568/68806.topojson
3. The result should have roads with `landuse_kind` properties. The test would fail if these were absent, or you got an HTTP 500 error.

I just tested that, and it passed. To double-check, look at the last-modified time in S3 (https://s3.amazonaws.com/mapzen-tiles-dev-us-east/20151214/fcd98/osm/all/17/49568/68806.json) which is Tue, 15 Dec 2015 18:37:28 GMT, and verify that it has only just been generated.

**Comment by zerebubuth** [comment]
Verified again, this time with tile 18/88824/141101.

**Comment by rmarianski** [comment]
Verified with: 15/9629/12316.
