### ISSUE TITLE
ERROR when run __init__.py

### ISSUE THREAD

**Issue by oongkung** [mapzen/tileserver#42]
root@mapsapi:~/tileserver# python tileserver/**init**.py config.yaml
Traceback (most recent call last):
  File "tileserver/**init**.py", line 546, in <module>
    tile_server = create_tileserver_from_config(config)
  File "tileserver/**init**.py", line 475, in create_tileserver_from_config
    os.path.dirname(queries_config_path))
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/command.py", line 413, in parse_layer_data
    resources = _parse_postprocess_resources(post_process_item, cfg_path)
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/command.py", line 338, in _parse_postprocess_resources
    *sys.exc_info()))))
Exception: Unable to init resource 'matcher' with function 'vectordatasource.transform.CSVMatcher' due to Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tilequeue/command.py", line 332, in _parse_postprocess_resources
    fn = resolve(init_fn_name)
  File "/usr/local/lib/python2.7/dist-packages/zope/dottedname/resolve.py", line 30, in resolve
    found = __import__(used)
ImportError: No module named vectordatasource

**Comment by nvkelso** [comment]
Please try the install walk through:
https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service

Sounds like you need to install all 3 project components (and are currently missing one).

_n

**Comment by oongkung** [comment]
I installed all 3 project through:
https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service
and got this error.

this is my file list
root@mapsapi:~# ls
env                  new-york_new-york.osm.pbf  tilequeue-config.yaml  tileserver.egg-info  vector_datasource.egg-info
logging.conf.sample  tilequeue                  tileserver             vector-datasource    wof_neighbourhoods.pgdump

**Comment by rmarianski** [comment]
Try running `python setup.py develop` from the vector-datasource directory.

**Comment by musicformellons** [comment]
I had same problem. It is not documented that you should also install pyaml, then error will go. I made an issue to address this this weekend.

**Comment by rmarianski** [comment]
pyyaml is listed in setup.py and the requirements file. I updated the getting started instructions to run setup.py develop from within the same directory.
