### ISSUE TITLE
Remove custom layer handling logic

### ISSUE THREAD

**Issue by rmarianski** [mapzen/tileserver#46]
Custom layer handling logic is done by [xonacatl](https://github.com/tilezen/xonacatl) now.

**Comment by nvkelso** [comment]
We'll also need to document in the vector-datasource wiki how to run Xonacatl locally along side tileserver.

**Comment by nvkelso** [comment]
We deferred Xonacatl in prod, so this is lower priority / blocked now.

**Comment by nvkelso** [comment]
Closing as architecture changed (rely on Tapalcatl or Xonacatl instead).

See also:

- https://github.com/tilezen/tapalcatl-py/issues/10
