### ISSUE TITLE
Python versions

### ISSUE THREAD

**Issue by pnorman** [mapzen/tileserver#49]
What python versions are supported?

**Comment by zerebubuth** [comment]
We use 2.7. I've personally tested with 2.7.6 and 2.7.12, but I think all 2.7.x versions should work.

I don't know if other versions would work out of the box, but I suspect not. I think we'd be interested in making it work for Py3, as long as the changes weren't too invasive. I don't know about 2.6 - @rmarianski, @iandees what do you think?

**Comment by iandees** [comment]
I don't think we do anything that would make supporting 3.x hard, but it would be some work. I bet we'd review/merge a PR to do it 😄 .

**Comment by iandees** [comment]
I'd say we should document that we use Python 2.7.x and go from there.

**Comment by rmarianski** [comment]
> I'd say we should document that we use Python 2.7.x and go from there.

:+1:

**Comment by pnorman** [comment]
fwiw, 3.5 doesn't work with a failure in installing the requirements.

**Comment by radumas** [comment]
>I'd say we should document that we use Python 2.7.x and go from there.

FYI I've added this to the Vector Source [Install Documentation](https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service#prepare-a-virtualenv)

**Comment by nvkelso** [comment]
@radumas thank you!

**Comment by nvkelso** [comment]
Closing as documented.
