### ISSUE TITLE
Add tileserver to pypi

### ISSUE THREAD

**Issue by pnorman** [mapzen/tileserver#51]
Is it possible to add tileserver to pypi? I could take this on, but would much rather a maintainer does so.

**Comment by rmarianski** [comment]
Yes, we discussed this a little bit before but opted to wait until somebody asked for it, and here we are :)

It'll imply that all dependent packages are also on pypi, which from a cursory glance looks to be just [tilequeue](https://github.com/tilezen/tilequeue). The work there should mostly be just writing a readme to describe how that might be used.

Longer term it might make more sense to split up the code in tilequeue a little bit more. Right now I see it responsible for 2 things:
1. API for fetching data, processing, and formatting tiles, as well as some utility functions
2. Operational structure for how Mapzen processes tiles

Tileserver only needs to depend on the first part, and I'm assuming that the 2nd is more specific to Mapzen and less useful to others.

But for now, I think we should just publish our existing structure to pypi and possibly make another issue if we want to split up the repo. Any further thoughts @zerebubuth, @iandees, @nvkelso ?

**Comment by nvkelso** [comment]
Pub now, file an issue to split it up for a rainy day.

**Comment by pnorman** [comment]
👍 to pub now, 2.0 can be a split if desired.

> Operational structure for how Mapzen processes tiles

What does this consist of?

**Comment by rmarianski** [comment]
> > Operational structure for how Mapzen processes tiles
> 
> What does this consist of?

Managing the tile processing pipeline we have on running on aws, eg sqs, redis, s3.

**Comment by pnorman** [comment]
Everything except tilequeue is now being pulled from pypi, so it's just it left. Should I open an issue on its repo?

**Comment by nvkelso** [comment]
I've added https://github.com/tilezen/tilequeue/issues/220 – but we also have Dockerization in the mix via https://github.com/tilezen/tileserver/pull/93 so a few different planes in the air right now.

**Comment by pnorman** [comment]
Anything I can do to help on this?

**Comment by nvkelso** [comment]
@rmarianski can you take a fresh look at this, please?

**Comment by rmarianski** [comment]
Apologies for this taking so long. I'll go ahead and push over the latest vector-datasource, tileserver, and tilequeue releases to pypi tomorrow morning.

**Comment by rmarianski** [comment]
`vector-datasource`, `tileserver`, and `tilequeue` have been published to pypi.
