### ISSUE TITLE
Cut zoom content for 17+ requests from z16 tiles

### ISSUE THREAD

**Issue by nvkelso** [mapzen/tileserver#64]
Instead of doing a fresh DB request for the zoom 17+ tile bounds, we should get the parent zoom 15 ~~16~~ tile and from it cut the zoom 16+ ~~17+~~ content (since 2x2 metafiles at 512px size are starting to be a thing).

**Comment by rmarianski** [comment]
Related to https://github.com/mapzen/tile-tasks/issues/189

**Comment by nvkelso** [comment]
Similar was completed for Tilequeue in https://github.com/tilezen/tilequeue/pull/158.

**Comment by nvkelso** [comment]
Replaced with: https://github.com/tilezen/tapalcatl-py/issues/20
