### ISSUE TITLE
Could not run v1.3.0

### ISSUE THREAD

**Issue by hriad** [mapzen/tileserver#75]
Hello,
I've followed the install instructions located [here](https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service)

However when trying to run tileserver I get the following error:

> Traceback (most recent call last):
  File "tileserver/__init__.py", line 19, in <module>
    from tilequeue.metatile import make_single_metatile, extract_metatile
ImportError: cannot import name make_single_metatile

I didn't get any error during install, so I really have no idea about what went wrong.

**Comment by nvkelso** [comment]
vector-datasource `v1.1.0` requires: tileserver `v1.3.0` and tilequeue `v1.4.0` and mapbox-vector-tile `v1.0.0`. You'll need to ensure your checkout is to that specific git tag (not master which is default).

**Comment by hriad** [comment]
Yes I made sure to checkout the correct releases as per vector-datasource release notes

**Comment by hriad** [comment]
I just redid the whole thing, and made sure to checkout the correct releases. Yet I get the same result. Interestingly, If I follow the install steps but run off master instead of the tagged releases, tileserver is able to start just fine.

**Comment by zerebubuth** [comment]
> ImportError: cannot import name make_single_metatile

The `make_single_metatile` function was [recently removed](https://github.com/tilezen/tilequeue/pull/163) from tilequeue, although it is [present in the v1.4.0 release](https://github.com/tilezen/tilequeue/blob/v1.4.0/tilequeue/metatile.py#L8). Sometimes I find that `pip` installs multiple versions of libraries in my virtualenv and uses a different version than I expected. From time to time I have to have a "clear out" and re-make the virtualenv to make sure there's only one version for each library. Is it possible that you've got both the master and v1.4.0 versions of tilequeue, and tileserver v1.3.0 is finding the master version of tilequeue?

**Comment by hriad** [comment]
I tried with a clean virtualenv, but got the same result. However your comment got me in the right direction. Specifying `tilequeue@v1.4.0` instead of `tilequeue@master` in requirements.txt did the trick for me. Now tileserver is working!

**Comment by zerebubuth** [comment]
Glad to hear it, and sorry about the confusion!

I've added a follow-up issue in #76 to figure out whether it's better to fix this in `requirements.txt` or the installation instructions.
