### ISSUE TITLE
Should we specify fixed versions in tagged releases?

### ISSUE THREAD

**Issue by zerebubuth** [mapzen/tileserver#76]
We currently specify the master branch for tilezen software dependencies in [`requirements.txt`](https://github.com/tilezen/tileserver/blob/3b8d7df88e641a6aa1c561f1c6b3009fc8e37667/requirements.txt#L25-L26), although we specify fixed, non-master versions in the [vector-datasource release notes](https://github.com/tilezen/vector-datasource/releases/tag/v1.1.0). This is confusing, since [the installation instructions say to install requirements from `requirements.txt`](https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service#install-python-dependencies). We should fix versions in `requirements.txt` or provide different installation instructions which install fixed versions.

See #75 for context.

**Comment by pnorman** [comment]
👍 to changing requirements.txt

**Comment by nvkelso** [comment]
+1 This keeps coming up in GH support issues.
