### ISSUE TITLE
Not returning all information like roads, buildings, etc

### ISSUE THREAD

**Issue by Martinlck** [mapzen/tileserver#80]
Hello I have successfully setup the tile server and imported the data from the docs, but when I run it against a javascript client the information that I receive from the endpoint does not contain streets or anything so my app draws an incomplete map. 
Do you have any idea why this would be happening? Am I doing something wrong?
Thanks.

**Comment by nvkelso** [comment]
Hi @Martinlck Did you follow the instructions on https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service? 

That wiki exercise will load an extract for New York city, United States. Are you testing valid tiles inside that New York city bounding box? Do any other layers draw? (And Tilezen calls them roads not streets.)

**Comment by Martinlck** [comment]
Hi @nvkelso  I did follow up all the instructions, sorry for the wrong wording, yes roads, I only get to see major roads, but when I zoom in, the small roads are not being shown and there is some missing things so the map looks incomplete, actually the only layer that I get a response from is for points of interest, the other ones are empty. I am testing valid tiles inside the new york city.

**Comment by nvkelso** [comment]
Can you provide a screenshot, please? Is there a public testing URL I can look at, or baring that a GeoJSON tile you can attach to this issue?

**Comment by nvkelso** [comment]
Did you make sure to checkout the specific tags in each of the repos rather than using master?

**Comment by Martinlck** [comment]
@nvkelso Hmm I think I used master, that might be the cause of the problem, let me try re-doing it again and if I still have the problem I will share with you a screenshot and a public testing URL.

**Comment by nvkelso** [comment]
Looks like it's: 

- https://github.com/tilezen/vector-datasource/releases/tag/v1.1.0
- Requires: tileserver v1.3.0 and tilequeue v1.4.0 and mapbox-vector-tile v1.0.0.

**Comment by mattscamp** [comment]
Hey @nvkelso . I just made sure all versions are in sync, but the issue is still there. Attached is an image of the area and response eg.

![screen shot 2560-03-22 at 12 54 12 pm](https://cloud.githubusercontent.com/assets/2180254/24184090/cb1ab74e-0efe-11e7-9292-ded05f90bef1.png)

I then ran a query to see how many buildings are within a small area of this. (0.001 degrees)
<img width="380" alt="screen shot 2560-03-22 at 1 00 26 pm" src="https://cloud.githubusercontent.com/assets/2180254/24184230/90d4ac06-0eff-11e7-8313-d0059bdb8027.png">

**Comment by nvkelso** [comment]
I see what you mean! Is the same true when you zoom out? Can you count the
lines with highway tags in your DB to make sure they imported correctly?

**Comment by mattscamp** [comment]
Yeah, same on every zoom level. Note, we just have Singapore data in the db. Thanks!
<img width="657" alt="screen shot 2560-03-22 at 1 30 14 pm" src="https://cloud.githubusercontent.com/assets/2180254/24185065/c1170888-0f03-11e7-94aa-9f13b97df4b3.png">

**Comment by Martinlck** [comment]
Any clues? Any solution? I installed it all over again and I still have the same problem. @nvkelso 
I'm thinking there might be some missing relation and that's why the data is not being pulled, but I'm unable to identify which or why.

**Comment by rmarianski** [comment]
Are you using the metro extract from here? https://mapzen.com/data/metro-extracts/metro/singapore/

**Comment by mattscamp** [comment]
@rmarianski We tried both the PBF from that URL and restarting from scratch with another raw OSM extract, both with the same result. Both times were following the installation instructions exactly. We also tried the NYC PBF from the installation instructions as well.

**Comment by mattscamp** [comment]
Not sure if this is helpful, but here is all the tables in the DB with row counts.
![screen shot 2560-03-24 at 8 42 37 am](https://cloud.githubusercontent.com/assets/2180254/24277169/013e748a-106e-11e7-9f39-fb1bafa65e03.png)

**Comment by Martinlck** [comment]
Hello, we managed to get it to work, we were using ubuntu 16 and when we changed to ubuntu 14 it worked perfectly fine. Apparently there is something wrong with latest ubuntu.

**Comment by rmarianski** [comment]
Whoa, that's odd and a good find on your part. Thanks for posting the conclusion.

**Comment by nvkelso** [comment]
I've updated https://github.com/tilezen/vector-datasource/wiki/Mapzen-Vector-Tile-Service with a note that Ubuntu 16 has issues, bolding the Ubuntu 14 recommendation.

**Comment by zerebubuth** [comment]
I think this is because [our PPA](https://launchpad.net/~tilezen/+archive/ubuntu/ppa) only contains the trusty (14.04) package, and we didn't build a xenial (16.04) package. Therefore it'll fall back to the Ubuntu version of the package, which looks like it's too old to contain the [fixes](https://github.com/tilezen/osm2pgsql/tree/mz-integration) we made, which I think only made it into a released version of `osm2pgsql` at release 0.92.
